main: com.plochem.ssa.SSkyblockAddon
name: sSkyblockAddon
version: 1.8.3
author: Plochem
description: Skyblock Addon for Straxidus.
depend: [Vault, Citizens]
loadbefore: [ASkyBlock, ShopGUIPlus]
commands:
   giveBouncePad:
   bal:
   balance:
   pay:
   setbal:
   addbal:
   boosterqueue:
   myboosters:
   givebooster:
   spawn:
   pvp:
   kits:
   kit:
   createkit:
   tpa:
   tpaccept:
   tpdeny:
   invsee:
   givesellwand:
   givegen:
   sethome:
   home:
   delhome:
   homes:
   menu:
   baltop:
   help:
   clearchat:
   rewards:
   giveBanknote:
   withdraw:
   trade:
   setspawn:
   setpvpspawn:
   setKillLb:
   setDeathLb:
   ores:
   tags: